local discovery = require("nvim_cpp_ide.agent.discovery")
local project_path = require("nvim_cpp_ide.project.path")

local M = {}

M.generated_marker = "<!-- generated by nvim-cpp-ide :AgentInit -->"

local function portable_arg(root, value)
  value = tostring(value)
  if not project_path.is_absolute(value) then
    return value
  end

  local normalized_root = vim.fs.normalize(root)
  local normalized_value = vim.fs.normalize(value)
  if normalized_value == normalized_root then
    return "."
  end

  local prefixes = {
    normalized_root .. "/",
    normalized_root .. "\\",
  }
  for _, prefix in ipairs(prefixes) do
    if vim.startswith(normalized_value, prefix) then
      return "./" .. normalized_value:sub(#prefix + 1)
    end
  end
  return value
end

local function argv_display(root, argv)
  local portable = {}
  for i, value in ipairs(argv or {}) do
    portable[i] = portable_arg(root, value)
  end
  return vim.json.encode(portable)
end

local function task_lines(ctx)
  local lines = {}
  for _, action in ipairs(ctx.task_order or {}) do
    local task = ctx.tasks[action]
    if task and task.available then
      table.insert(lines, ("- **%s** argv: `%s`"):format(action, argv_display(ctx.root, task.argv)))
    else
      local reason = task and task.reason or "not resolved"
      table.insert(lines, ("- **%s**: unavailable — %s"):format(action, reason))
    end
  end
  return lines
end

local function structure_lines(ctx)
  local lines = {}
  if #ctx.directories == 0 then
    table.insert(lines, "- No non-generated top-level directories were discovered.")
  else
    for _, name in ipairs(ctx.directories) do
      table.insert(lines, ("- `%s/`"):format(name))
    end
  end

  if #ctx.markers > 0 then
    table.insert(lines, "")
    table.insert(lines, "Important repository files detected:")
    for _, name in ipairs(ctx.markers) do
      table.insert(lines, ("- `%s`"):format(name))
    end
  end
  return lines
end

function M.render(ctx)
  local backend = ctx.backend or "custom / unresolved"
  local lines = {
    M.generated_marker,
    "# AGENTS.md",
    "",
    "This file defines repository-level working instructions for coding agents. Keep provider-specific settings outside this file.",
    "",
    "## Project",
    "",
    ("- Name: `%s`"):format(ctx.name),
    "- Root: repository root (`.`)",
    ("- Detected build backend: `%s`"):format(backend),
  }

  if ctx.config_file then
    table.insert(lines, ("- nvim-cpp-ide task config: `%s`"):format(vim.fs.basename(ctx.config_file)))
  end

  vim.list_extend(lines, {
    "",
    "## Repository structure",
    "",
  })
  vim.list_extend(lines, structure_lines(ctx))

  vim.list_extend(lines, {
    "",
    "## Build and validation contract",
    "",
    "Use the resolved project tasks below instead of guessing build-system invocations. Commands are represented as argv JSON arrays so the contract is independent of shell quoting rules.",
    "",
  })
  vim.list_extend(lines, task_lines(ctx))

  vim.list_extend(lines, {
    "",
    "When nvim-cpp-ide is available, the same action vocabulary is exposed through:",
    "",
    "```text",
    "nvim --headless '+ProjectTask configure' +qa",
    "nvim --headless '+ProjectTask build' +qa",
    "nvim --headless '+ProjectTask test' +qa",
    "nvim --headless '+ProjectTask lint' +qa",
    "nvim --headless '+ProjectTask format' +qa",
    "```",
    "",
    "A failed headless project task returns a non-zero exit status.",
    "",
    "## Runtime context bridge",
    "",
    "When `.nvim-agent/context.json` or `.nvim-agent/context.md` exists, treat it as an advisory snapshot of the developer's current Neovim runtime state. It can include diagnostics, Git status/diff summaries, current file/symbol focus, resolved project tasks, last task results, and Quickfix entries.",
    "",
    "Regenerate it from Neovim with `:AgentContext` when runtime state changes materially. Do not treat the snapshot as a substitute for reading the repository itself, and do not assume it contains full file contents or a complete Git patch.",
    "",
    "## Working rules",
    "",
    "- Read the relevant repository documentation and nearby code before editing.",
    "- Keep changes scoped to the requested task; avoid unrelated refactors.",
    "- Preserve existing public interfaces unless the task explicitly requires changing them.",
    "- Do not edit generated build output or vendored dependencies unless the task explicitly requires it.",
    "- Run the relevant build, test, lint, and format tasks after changes when those tasks are available.",
    "- If a validation task fails, report the command, failure, and remaining risk instead of claiming success.",
    "- Review the final diff before considering the task complete.",
    "",
    "## Agent-specific files",
    "",
    "Provider-specific launch configuration belongs in the agent runtime or editor configuration. `AGENTS.md` remains the shared repository contract. `.nvim-agent/` contains disposable runtime snapshots and should not be committed.",
    "",
  })

  return table.concat(lines, "\n")
end

function M.render_project(opts)
  return M.render(discovery.inspect(opts))
end

function M.claude_bridge()
  return "@AGENTS.md\n"
end

return M
