name: "🐛 Bug report"
description: 报告问题并帮助我们复现
labels: [bug]
body:
  - type: checkboxes
    attributes:
      label: 预检查
      options:
        - label: 我已使用最新的 main/Release 测试
          required: true
  - type: input
    attributes: { label: 操作系统/终端, placeholder: "Ubuntu 22.04 / Windows Terminal" }
  - type: input
    attributes: { label: Vim/Neovim 版本, placeholder: "nvim --version" }
  - type: textarea
    attributes: { label: 复现步骤, placeholder: "1) ... 2) ... 3) ..." }
    validations: { required: true }
  - type: textarea
    attributes: { label: 日志/截图/录屏 }
